### ISSUE TITLE
Zone R0 after clearing BCNM 40 Undying Promise caused chest not to spawn.

### ISSUE THREAD

**Issue by Aeniesh** [HorizonFFXI/HorizonXI-Issues#880] opened 2023-01-19 20:00 UTC
My group cleared Undying Promise and right after, we all got R0. When we were able to return, we all lost BCNM status and the chest was not there. We were left in the BCNM. GM Ticket was submitted immediately after.

**Comment by XIBrixy** [comment] 2023-01-21 02:33
![1](https://user-images.githubusercontent.com/121909533/213840065-3f63967c-413f-4e76-8ebf-b67ac428d447.png)
Can confirm. Happed to our group twice in a row as well. Avoid this BCNM until fixed.

**Comment by CriticalXI** [comment] 2023-03-06 19:59
Duplicate of #821

**Closed by CriticalXI** 2023-03-06 19:59 UTC
