### ISSUE TITLE
🐛[BUG][Combat] - Summoner Pet Damage

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#25] opened 2022-09-04 03:49 UTC
**What does this bug affect?**
Summoner pet physical blood pacts are doing 0 damage on all mobs.

**Steps to Reproduce**
Summon an avatar and use a physical blood pact on any mob and check the log for the damage.

**Expected behavior**
Physical blood pacts should be doing damage, especially the level 70 BPs which should be doing the most damage.

**Screenshots**
N/A

**Setup Information**
Version 30220802_3

**Additional context**
Magic BPs are doing damage, although may be a little low / heavily resisted. All physical BPs are doing 0 damage regardless of what mob you fight. As a level 75 summon it was doing 0 damage to Vultures in Gustaberg.

**Comment by CriticalXI** [comment] 2022-09-13 20:03
Duplicate of #23

**Closed by CriticalXI** 2022-09-13 20:03 UTC
Labels: bug
