### ISSUE TITLE
🐛[BUG] Proto Omega issues

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#323] opened 2022-10-29 01:28 UTC
**What does this bug affect?**

At the start of the fight it instantly swaps to 2 legs and spawns a gunpod.
A ton of its tp moves don't work correctly:
 - Stun cannon doesnt stun or paralyze and does 0 damage 
 - Hyperpulse does 0 damage with no gravity or bind 
 - Floodlight does 0 damage with no blind or silence 
 - Ion efflux doesn't paralyze 
 - Rear lasers doesn't petrify or do damage 
 - Sometimes hyperpulse is single target and uses incorrect animation in its 4 leg form. May be using wrong name. 
 - Laser shower doesn't have reduced damage fighting at an angle or increased damage when the target is directly hit. 
 Proto omega's name in 2 legs form shifts up and down when it auto attacks.Proto omega used discharger which I believe is only supposed to be used my regular story omega.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by jmcmorris** [comment] 2022-11-03 22:43
Closing this as a duplicate of https://github.com/HorizonFFXI/HorizonXI-Issues/issues/327

**Closed by jmcmorris** 2022-11-03 22:43 UTC
Labels: bug
