### ISSUE TITLE
🐛[BUG][System]

### ISSUE THREAD

**Issue by shinycat91** [HorizonFFXI/HorizonXI-Issues#681] opened 2023-01-04 00:45 UTC
**What does this bug affect?**

Changed jobs in a moghome in Jueno and I am unable to change to any other job everything is unselectable

**Screenshots**

https://imgur.com/a/h52JNtz

**Comment by BayaniTenzen** [comment] 2023-01-05 16:03
duplicate of #688

**Closed by BayaniTenzen** 2023-01-05 16:03 UTC
Labels: bug, Duplicate
