### ISSUE TITLE
🐛[BUG]Diabolos Nightmare BP

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#42] opened 2022-09-05 03:24 UTC
**What does this bug affect?**

BP says it does 0 damage. Nothing happens at all.
**Steps to Reproduce**

Summon Diabolos and use the nightmare BP on any mob. Nightmare has no effect.
**Expected behavior**

Sleep with a DOT.
**Screenshots**

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment] 2022-09-13 20:06
Duplicate of #34

**Closed by CriticalXI** 2022-09-13 20:07 UTC
Labels: bug
