### ISSUE TITLE
🐛[BUG]Cobalt Jellyfish are being classified as an item and not a fish and so gives incorrect catch message.

### ISSUE THREAD

**Issue by ZellithS** [HorizonFFXI/HorizonXI-Issues#1194] opened 2023-03-04 17:02 UTC
BUG
**What does this bug affect?**
Cobalt Jellyfish seem to be an item.  Instead of "something catching the hook"; which is done for all fish, it gives the "pulling at your line" text, which is used almost exclusively for items.  The bite rate also seems to be very low, with most attempts of catching something "pulling at your line" being generic items like rusty buckets and subligars.

**Steps to Reproduce**
Go fishing in an area where you can normally catch cobalt jellyfish.  I did my testing in north ocean in batallia downs with composite and fly lure.

**Expected behavior**
Iirc it SHOULD say "something caught the hook".  Not to mention the catch rate should be significantly higher.

**Screenshots**
![image](https://user-images.githubusercontent.com/59283576/222918947-5cf64964-7e34-4832-bbfb-d1089a49b268.png)

**Setup Information**
Windows 10.  

**Additional context**
Based on my reading on the forums, others have also noted Cobalt Jellyfish are classed as items, with a very low catch rate - and not as a fish.  Im unsure if this is an intentional change.  Seems like it would be inconsistent if it was, so Im leaning towards it being a bug.  Feel free to tell me I'm being stupid though.

**Comment by siknoz** [comment] 2023-12-14 06:14
This can be closed as expected behavior. Pulling from a retail capture this is what it looks like in the log which is the same as rusty items. So messaging is correct.

![image](https://github.com/HorizonFFXI/HorizonXI-Issues/assets/78240569/0e4cf403-a390-45f1-ab42-3edc2cb3c34e)

**Comment by hookstar** [comment] 2023-12-14 11:01
Concur this is the way.

**Closed** 2023-12-14 11:02 UTC
Labels: bug
