### ISSUE TITLE
🐛[BUG] Limbus SW Apollyon bug

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#284] opened 2022-10-23 01:53 UTC
**What does this bug affect?**

Couldnt open the chests at all that spawned in SW Apollyon.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by jmcmorris** [comment] 2022-10-23 15:52
Unable to reproduce and need more details

**Comment by Birdy-gif** [comment] 2022-10-23 16:00
Not aure if this matters but when we first started limbus some of us in the alliance weren’t able to enter even with the buff icon. Throughout that entire run none of the chests could be opened at all by anyone. Our second run we had the same issues with some players not able to enter but we could open the chests that time. Not exactly sure how to reproduce it but it could be an issue that pops up in the future.

**Comment by jmcmorris** [comment] 2022-10-23 16:43
Thanks!

I fixed players being unable to enter on LSB a few days ago and that needs to be merged into ASB. https://github.com/LandSandBoat/server/pull/2996

I think these issues may in part be caused by that.

**Comment by jmcmorris** [comment] 2022-11-02 15:15
Closing as I am fairly certain this is fixed and now merged into ASB.

**Closed by jmcmorris** 2022-11-02 15:15 UTC
Labels: bug
