### ISSUE TITLE
🐛[BUG][Quest] You Call That A Knife quest missing

### ISSUE THREAD

**Issue by Tenacious-C** [HorizonFFXI/HorizonXI-Issues#1162] opened 2023-03-02 02:38 UTC
**What does this bug affect?**
NPC does not give quest: https://ffxiclopedia.fandom.com/wiki/You_Call_That_a_Knife%3F

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by CriticalXI** [comment] 2023-04-18 18:43
Duplicate of #1170

**Closed by CriticalXI** 2023-04-18 18:43 UTC
Labels: Missing Content
