### ISSUE TITLE
🐛[BUG][Combat] Issues with Prelude and Etudes

### ISSUE THREAD

**Issue by montijin** [HorizonFFXI/HorizonXI-Issues#373] opened 2022-11-04 19:58 UTC
**What does this bug affect?**

Currently you cannot target other players with etudes or Preludes, it's set to self cast only. 
Etudes are also AoE instead of the era setting of being single target. 

**Steps to Reproduce**

Log onto the test server and try the bard songs.

**Expected behavior**

Etude - Single target & targetable
Prelude - Single target & targetable

**Screenshots**
Version Update (12/12/2012)
![image](https://user-images.githubusercontent.com/2160211/200063954-cb1033b7-6046-4688-a864-ee3e03d058df.png)

**Additional Information**
11/4/2022 test server

**Comment by hookstar** [comment] 2022-11-06 02:02
After some messing around and changing the bits, I am not able to make preludes target party member. I think this might have something to do with dats as well? Going to need an assist on this one, sorry.

**Comment by hookstar** [comment] 2022-11-06 02:03
However, using Pianissimo does allow to cast on party member at current build.

**Comment by CriticalXI** [comment] 2022-11-07 06:48
The change needs to happen in both the SQL and in DATS. So if you can make the change in the code, we can have the DATs editted to finish it.

**Comment by hookstar** [comment] 2022-11-07 13:55
Sounds good. It should be three for the bit (player and player party) a little challenging to test but will get it out.

**Comment by Squinkerdoodle** [comment] 2022-12-10 17:36
Commenting with another etude / prelude report: https://github.com/HorizonFFXI/HorizonXI-Issues/issues/464

**Comment by Squinkerdoodle** [comment] 2022-12-10 17:37
@hookstar did you do this for Etude songs as well or was it only Prelude so far?

**Comment by hookstar** [comment] 2022-12-10 18:57
> @hookstar did you do this for Etude songs as well or was it only Prelude so far?

Looks like I apparently only did preludes. We're the days changed to reflect?

**Comment by StyrkaGG** [comment] 2022-12-10 19:03
i just checked this now etudes are still aoe cant target and prelude can not target but is not aoe

**Comment by Squinkerdoodle** [comment] 2022-12-10 19:05
When checking this with Zawa we found that the Prelude can't manually target, but still works with a macro when targeting.

**Comment by hookstar** [comment] 2022-12-10 19:20
Yea that might be a dat thing then.. Not sure.. When I get back later, I can look into the etudes as well. But just to confirm, they should only be single target party, right?

**Comment by Squinkerdoodle** [comment] 2022-12-11 00:11
Right, single target only. https://ffxiclopedia.fandom.com/wiki/Etude?oldid=35778

**Comment by hookstar** [comment] 2022-12-11 18:31
Ah, so looking at it Etudes are in the era_spell_list as single target, thats prolly what I didn't change them. It appears it would need to be some dat changes I believe?

**Comment by CriticalXI** [comment] 2022-12-11 18:39
DATs only control who you can target with the spell, the AOE part of it should be SQL side I believe.

**Comment by hookstar** [comment] 2022-12-11 18:51
I thought so, they should be correct on the sql side.

**Comment by Squinkerdoodle** [comment] 2022-12-11 19:33
So this is something that should work as intended on Horizon, and just isn't on the test server?

**Comment by hookstar** [comment] 2022-12-11 19:36
I would imagine so if the dats have not translated over to your testing environment.

**Comment by Squinkerdoodle** [comment] 2022-12-11 20:10
Would anyone with the dats be able to check this for us, just to see if we can close this one out or not.

**Closed** 2023-01-09 14:30 UTC
Labels: bug
