### ISSUE TITLE
[BUG][System/Item] Republic Hammer's damage is lower than the expected 21.

### ISSUE THREAD

**Issue by TheUndeadFish1** [HorizonFFXI/HorizonXI-Issues#812] opened 2023-01-12 11:05 UTC
My republic hammer still has a damage value of 18 instead of the expected value of 21. All other hammers had their damage increased by 3 to make them viable. This includes the NQ of the weapon "Bastokan Hammer" which has its damage correctly set at 20.

![Bugged Hammer](https://user-images.githubusercontent.com/3422025/212051673-eddf1d24-2ae9-41a2-972d-a1ce9e77ac89.png)

**Comment by CriticalXI** [comment] 2023-03-06 19:15
Duplicate of #772

**Closed by CriticalXI** 2023-03-06 19:15 UTC
