### ISSUE TITLE
🐛[BUG] Below the Ark -> Access to Escha Zi'tah

### ISSUE THREAD

**Issue by RicardoFAndres** [HorizonFFXI/HorizonXI-Issues#936] opened 2023-01-26 11:22 UTC
I´m doing Below the Ark for do Promys and when i clicked Shattered Telepoint, The Path Untraveled starts with Lion talking me about Iroha and a option for travel to lower jeuno, delkfutt's tower and qufim.

**Steps to Reproduce**
I´m only doing CoP missions like the FFXIclopedia guide shows

**Screenshots**
https://gyazo.com/e40a65c354777bc34d7955466462dce1

**Setup Information**
Windows 11, Horizon Client but launcher is Windower

PS: Clicked on Qufim option (like the original RoV quest) and touching again Shattered Telepoint continues to Below the Ark.

**Comment by TracentEden** [comment] 2023-02-04 23:00
duplicate of https://github.com/HorizonFFXI/HorizonXI-Issues/issues/843

**Closed by TracentEden** 2023-02-04 23:00 UTC
Labels: bug
