### ISSUE TITLE
🐛[BUG][System] gardening

### ISSUE THREAD

**Issue by peepers2023** [HorizonFFXI/HorizonXI-Issues#1311] opened 2023-03-25 23:09 UTC
**What does this bug affect?**

**Steps to Reproduce**
second batch of grain seeds with hume, bastok. only 9 out of 10 pots would grow.
first batch with galka, in windurst, 10/10 pots will grow
****

**Expected behavior**
all pots should be growing.

**Screenshots**
![Screenshot 2023-03-25 150403](https://user-images.githubusercontent.com/128939938/227746605-fa972479-0cc2-4d05-861f-10ecbe2a4f3f.png)

**Setup Information**
windows 11

**Additional context**
will update what happens when i have a taru in bastok attempt to garden.

**Comment by CriticalXI** [comment] 2023-04-18 20:01
Duplicate of #764

**Closed by CriticalXI** 2023-04-18 20:01 UTC
Labels: bug
