### ISSUE TITLE
When I speak to NPC and AH 2-3x a day I get frozen and have to !unstuck 🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/Website]

### ISSUE THREAD

**Issue by Magnuss7654** [HorizonFFXI/HorizonXI-Issues#655] opened 2023-01-02 22:56 UTC
**What does this bug affect?**

**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by Magnuss7654** [comment] 2023-01-02 22:57
Effects me

**Comment by HitGubz** [comment] 2023-01-03 00:31
I have only ever got this bug after entering MH and interacting with Moogle, then interaction with NPC or AH freezes me. I also just relog which fixes it and it's quicker than unstuck, assuming you can get back in quickly.

**Comment by BayaniTenzen** [comment] 2023-01-05 16:11
duplicate of #661

**Closed by BayaniTenzen** 2023-01-05 16:11 UTC
Labels: bug, Duplicate
