### ISSUE TITLE
Cerment Headstone in Behemoth's Dominion broken

### ISSUE THREAD

**Issue by valeforheya** [HorizonFFXI/HorizonXI-Issues#1187] opened 2023-03-04 04:38 UTC
**What does this bug affect?**   unable to get lighting fragment for ZM 5

headstone for lighting fragment will only spawn monsters and not give fragment. attempted to zone, logout and all options in players ability to get item
**Steps to Reproduce**

atempted 5 kills, zoned, logged out
**Expected behavior**

after kill should be able to click headstone for key item for ZM 5
**Screenshots**

**Setup Information**

**Additional context**

![Valeforheyas_2023 03 03_232210](https://user-images.githubusercontent.com/51164904/222875850-b9f98693-756c-46da-8100-5c2991da52bf.png)
![Valeforheyas_2023 03 03_232223](https://user-images.githubusercontent.com/51164904/222875852-35fd5711-b59c-4be3-aaa4-c7305e95697a.png)
![Valeforheyas_2023 03 03_232229](https://user-images.githubusercontent.com/51164904/222875855-5bdb5f3e-0836-4d6a-aa45-6dd6cb7c3497.png)
![Screenshot (480)](https://user-images.githubusercontent.com/51164904/222875930-09cdc3e0-b225-43a5-9015-ec7e5ba5caeb.png)

**Comment by hookstar** [comment] 2023-03-06 14:25
Was this true for everyone in  your group?

**Comment by valeforheya** [comment] 2023-03-06 16:09
yes, 3 members needed the headstone. all tryed same steps as me, log out. zoning and reforming groups so players needing the headstone were in same party. no matter methoud we tryed it didnt work. even tryed only person who spawned click for item. didnt work. members that needed at time was myself (valeforheyas) mario and floop. because of logout didnt think to screen shot 1st 2ed and 3ed spawns. only got 4th and 5th.

**Comment by hookstar** [comment] 2023-03-06 16:33
Have you put in a GM ticket as well? I am unable to replicate this and it doesnt seem to be a wide spread issue.

**Comment by hookstar** [comment] 2023-03-06 17:02
Ok, may have just been an isolated incident. Closing for now as I cannot reproduce it.

Thanks!

**Closed by hookstar** 2023-03-06 17:02 UTC
Labels: bug
