### ISSUE TITLE
🐛[BUG] Dynamis-Valkurm Issues

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#146] opened 2022-09-27 15:14 UTC
**What does this bug affect?**
Beastmen mobs / statues are dropping currency from other cities in addition to their own. Example: quadav mobs & statues dropping sandy/windy currency in addition to bastok currency, orc mobs & statues dropping bastok/windy currency in addition to sandy currency. (Not sure if this is supposed to be how it is or not, and I know Goblin mobs & status can drop all 3)

Mega boss morbol Cirrate Christelle still uses TP moves Putrid Breath / Miasmic Breath / Fragrant Breat / Vampiric Lash after the 4 NMs which should lock those moves have been killed. It seems the additional lock is working (locked speed so it's normal speed, unable to summon nightmare morbols, etc)

Statues 25 through 32 are spawning in and aggroing (thus summoning their groups) when the mega boss morbol is pulled instead of after it's defeated.

**Expected behavior**
Beastmen mobs / statues drop the currency for their city, aside from goblin mobs / statues which should drop all 3 currencies.

Defeating the below NMs should lock a TP move for the boss in addition to locking it's extra effect.
https://enedin.be/dyna/html/zone/val.htm
Defeating Fairy Ring should inhibit Christelle's TP move Miasmic Breath.
Defeating the Dragontraps should inhibit Christelle's TP move Putrid Breath.
Defeating Stcemqestcint should inhibit Christelle's TP move Vampiric Lash.
Defeating Nant'ina should inhibit Christelle's TP move Fragrant Breath.

The way it's worded the NM may still be able to use the TP move, but not have it's effect actually work like the Fragrant Breath's charm effect (which was still working with Nant'ina killed)

Statues 25 through 32 should spawn once the mega boss has been killed, and not aggro immediately.

![image](https://user-images.githubusercontent.com/112344508/192694947-1a318ece-9ec1-4780-948b-d29b68ad9758.png)

**Setup Information**
Version 30220906_0

**Comment by OpheliaXI** [comment] 2022-09-28 04:50
All non-beastmen NMs in Dynamis - Valkurm do not use auto attacks.

**Comment by Squinkerdoodle** [comment] 2022-09-28 04:56
Really? In the capture it was showing that they do, though it was the updated version with pop items instead of the original.

**Comment by Frankie-hz** [comment] 2022-09-28 05:36
Mega Boss wave fixed with: https://github.com/AirSkyBoat/AirSkyBoat/pull/444

**Comment by OpheliaXI** [comment] 2022-09-30 06:04
Cirrate's moves don't lock out like the other dreamlands, instead it changes duration, power, and different intricacies of the application. I have confirmed that they are properly applying when "locked out".

**Comment by OpheliaXI** [comment] 2022-09-30 06:33
I could not reproduce the issue of currency dropping incorrectly. I did modify a few drop IDs to help alleviate potential issues, but generally they aren't the issue. I'll chalk it up to a failed DB merge.

**Closed** 2022-09-30 23:50 UTC
Labels: bug, Awaiting External PR
