### ISSUE TITLE
🐛[BUG][Launcher]?

### ISSUE THREAD

**Issue by PrinceOfParallax** [HorizonFFXI/HorizonXI-Issues#835] opened 2023-01-14 15:30 UTC
**What does this bug affect?**
Can not launch.

**Steps to Reproduce**
I am not sure, I had a prior install - i removed and did a clean install on a new drive.

**Expected behavior**
All I do it launch

**Screenshots**
![image](https://user-images.githubusercontent.com/38820735/212479709-68ecc2ea-3356-43df-982c-8296afce6cd8.png)

**Setup Information**
Win 10 22H2

**Additional context**

**Comment by CriticalXI** [comment] 2023-03-06 19:23
Duplicate of #732

**Closed by CriticalXI** 2023-03-06 19:23 UTC
Labels: bug
