### ISSUE TITLE
🐛[BUG][Brakorbrik/Out of Depths]

### ISSUE THREAD

**Issue by Brisk172** [HorizonFFXI/HorizonXI-Issues#1323] opened 2023-03-28 17:02 UTC
**What does this bug affect?**
 I'm doing the quest "Out of Depths", but I think it's broken. I did the 1st part of the quest which involves trading the first 10 Hoary Bomb Ash to Brakorbrik. That worked. I then returned to Port Bastok to Ravorara. That worked. I returned back to Brakorbrik, but he gave me a Dusty Tome. I read on this Discord that I needed to trade an extra Bomb Ash, but the NPC is not doing anything. He's not taking the item or even talking back.

**Steps to Reproduce**
Start the quest with talking to Ayame (Metalworks)
Then talk to Ravorara (Port Bastok)
Then talk to Brakobrik (Oldton Movalpolos) and selet the option "I getting you"
Kill Ancient Bombs until 11 Hoary Bomb Ashes are collected.
Trade the Hoary Bomb Ash to Brakorbrik in the following order:
- Trade 1 for Dusty Tome
- Trade 2 for Pointed Jug
- Trade 3 for Cracked Club
- Trade 4 for Peeling Hairpin
Next return to Ravorara (Port Bastok) and talk to her 4 times for each key item received to get rewards.
With the last Hoary Bombash remaining, return to Brakorbrik in Oldon Movalpolos.  Trade it to him and he gives Dusty Tome again.

**Expected behavior**
That last trade of Hoary Bombash to Brakorbrik, he should of given the Old Nametag key item, but instead he gives the Dusty Tome.  There has been reports of this on Discord and workarounds.  One of them is to trade him twice at the last step to get the key item before returning to Ravorara.  I'm not sure what the GM did for the other players to restart the quest or fix it.

https://discord.com/channels/933423693848260678/1066717741517635645/1066717741517635645
https://discord.com/channels/933423693848260678/1066717741517635645/1084998557729292428

**Screenshots**

**Setup Information**
Windows 10

**Additional context**

**Comment by CriticalXI** [comment] 2023-04-18 20:27
Duplicate of #916

**Closed by CriticalXI** 2023-04-18 20:27 UTC
Labels: bug
