### ISSUE TITLE
🐛[BUG][System] Ten of Coins Spawns

### ISSUE THREAD

**Issue by raiku38** [HorizonFFXI/HorizonXI-Issues#1605] opened 2023-06-01 05:39 UTC
**What does this bug affect?**

Was attempting to farm Ten of Coins in the Outer Horutoto Ruins for the Ten of Coins Card, while there was only 1 Ten Cardian that was spawning within that room where the Ten Cardians spawn. We were in this room for several hours and didn't see a single spawn of the Ten of Coins monster. While reading wikis and looking at their versions for 2006 and even 2004 there should be 3 Cardians that are spawning in that room at a time, saying there are 3 different spawn points within the room
**Steps to Reproduce**

**Expected behavior**

Within this room for the Ten Cardians there should be three spawning in the room at a time not a single one. Even looking at the wiki page for the Ten of Coins you can see in the background of the picture of the Ten of Coins you can see the Ten of Swords is also spawned within that room as well
**Screenshots**

**Setup Information**

**Additional context**

**Comment by TracentEden** [comment] 2023-06-02 01:12
Duplicate of https://github.com/HorizonFFXI/HorizonXI-Issues/issues/1317 , thanks for reporting!

**Closed by TracentEden** 2023-06-02 01:12 UTC
Labels: bug
