### ISSUE TITLE
🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/Website]

### ISSUE THREAD

**Issue by JawnFF** [HorizonFFXI/HorizonXI-Issues#1455] opened 2023-04-19 13:16 UTC
**What does this bug affect?**

Chocobo Mazurka

**Steps to Reproduce**

Cast Chocobo Mazurka on yourself/others and cast magic on a mob/get attacked by a mob.

**Expected behavior**

Mazurka should wear off if you cast on a mob and if you are attacked by a mob.

**Screenshots**

![Zurka Bug](https://user-images.githubusercontent.com/131269943/233085822-09386916-be62-417f-832b-999dc82bbda7.png)

**Setup Information**

**Additional context**

Chocobo Mazurka should wear off as a result of actioning or being actioned by a mob. Currently the only thing making it wear off is if you melee the mob.

**Comment by CriticalXI** [comment] 2023-04-19 20:28
Duplicate of #1004

**Closed by CriticalXI** 2023-04-19 20:28 UTC
Labels: bug
