### ISSUE TITLE
🐛[BUG][NPC/Quest/Mission/System/Combat/Launcher/Website]

### ISSUE THREAD

**Issue by Digitty0105** [HorizonFFXI/HorizonXI-Issues#1105] opened 2023-02-21 18:19 UTC
Combat
**What does this bug affect?**
Being able to successfully melee and kill Urganites

Went to bibiki bay purgo Isle to fight urganite on beach near boat dock. Upon taking little health they go into their shell. They stay till 100% healed and continue to stay in shell. In shell my melee do 0 dmg thus unable to build tp and weapon skill for more dmg. Beat on one for over a minute and it never came out of shell. Went to a Toucan to build tp, Urganite followed and when I swapped to it to ws with tp gained from Toucan, Urganite went right back in shell. Few seconds later it went unclaimed and depopped.

**Steps to Reproduce**

Was on Thf/nin, go melee Coralline Urganite for abit to observe it’s behavior.
**Expected behavior**

Go into shell short time to heal but after some back and forth a high lvl melee should be able to kill it off. 
**Screenshots**

**Setup Information**

Unsure what info this is as I’m not very pc literate
**Additional context**

Would also be helpful if the era+ Urganite in Sau Champaign could drop Urganite shells as well. Farmed them for almost an hour with only seashell and couple white sand dropping

**Comment by CriticalXI** [comment] 2023-04-18 18:24
Duplicate of #357

**Closed by CriticalXI** 2023-04-18 18:24 UTC
Labels: bug
