### ISSUE TITLE
🐛[BUG] BCNM icon bug after wipe 

### ISSUE THREAD

**Issue by Birdy-gif** [HorizonFFXI/HorizonXI-Issues#198] opened 2022-10-12 01:04 UTC
**What does this bug affect?**

Wiped at a bcnm and when we got back to the zone we still had the bcnm buff icon and when we clicked the enter it gave the options to run away or stay.
**Steps to Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information**

**Additional context**

**Comment by dallano** [comment] 2022-10-12 20:25
Were the steps required to reproduce outside of the bounds a regular player can access? What I mean is did you use GM commands when this bug occurred? I can't replicate this bug. When I homepoint after a wipe, I lose my battlefield status. 

Also which battlefield did this occur in? Any other information that might be pertinent?

**Comment by Squinkerdoodle** [comment] 2022-10-14 19:39
I'm wondering if what happened is people got back in the zone before the entire party had homepointed so they got the buff again due to the bcnm technically still going on.

**Comment by dallano** [comment] 2022-10-17 17:08
@Squinkerdoodle Ah so likely not an issue that will happen live, as no way players could HP and get back to a BCNM in 5 minutes lol. If that's the case I think we should close this issue. Or at least try to recreate it before closing it to ensure this is what happened.

**Comment by Squinkerdoodle** [comment] 2022-10-17 17:58
I'm planning some KSNM testing tomorrow, so we can try to recreate if possible then and will go from there. If we can't and everything works fine (from a normal player's PoV) then I'll ping you to close this.

**Comment by dallano** [comment] 2022-10-19 05:47
@Squinkerdoodle How'd it go, boss? You guys able to recreate this this time around?

**Comment by Squinkerdoodle** [comment] 2022-10-19 05:56
No luck. It's a possible issue if you wipe and HP and then use !zone to get back before everyone has left the BC, but in normal play I don't think it will be an issue. Unless someone doesn't leave the BC before you run all the way back to it. But even then it should only put you in the failed BC if anything I'd think.

**Comment by OpheliaXI** [comment] 2022-10-20 17:55
> 

Under normal circumstances this is resolved, it is only when the BC is still considered active that the player's effect is added back. I will close this issue as the new BCNM script resolves all of these issues under normal play.

**Closed by OpheliaXI** 2022-10-20 17:55 UTC
Labels: bug
