### ISSUE TITLE
🐛[BUG][Combat] Summoner Avatar Diabolos Blood Pact: Ward Somnolence does no damage

### ISSUE THREAD

**Issue by Sundrix** [HorizonFFXI/HorizonXI-Issues#1361] opened 2023-04-04 17:04 UTC
**What does this bug affect?**

Somnolence, according to noble summoner vanguard Jimmayus, should have an ftp of 2 and no dINT scaling, dealing dark damage.

Currently on horizon Somnolence does 0 always.

**Steps to Reproduce**
Become a Summoner, Summon Diabolos, Activate Blood Pact: Ward and choose to use Somnolence on any target. From level 30 raptors outside of jeuno to Genbu, Somnolence is always dealing 0 damage.

**Expected behavior**

Somnolence should have an ftp of 2 and no dINT scaling, dealing dark damage.

**Screenshots**

https://cdn.discordapp.com/attachments/1061420232465469530/1092671527390040145/image.png

https://cdn.discordapp.com/attachments/1061420232465469530/1092671568599076894/image.png

https://cdn.discordapp.com/attachments/1061420232465469530/1092671954470834246/image.png

https://cdn.discordapp.com/attachments/1061420232465469530/1092671991418470410/image.png

https://cdn.discordapp.com/attachments/1061420232465469530/1092672084565565520/image.png

**Setup Information**
Surely this is irrelevant but I am on Horizon launcher 1.4 playing ffxi on a Win 10 machine with above average, good specs.

**Additional context**

Help!!

**Comment by Squinkerdoodle** [comment] 2023-04-04 23:20
I can confirm that I've also seen this on the live server over a wide range of lvl mobs as a 75 smn. Additionally this is occurring on the test server. The below screenshot is from a lvl 6 crab with me as a lvl 75 smn.

![image](https://user-images.githubusercontent.com/112344508/229943422-c75c13be-6c30-4425-a41c-9a34580a395a.png)

**Comment by CriticalXI** [comment] 2023-04-18 20:48
Duplicate of #48

**Closed by CriticalXI** 2023-04-18 20:48 UTC
Labels: bug
