### ISSUE TITLE
🐛[BUG][NPC/System] Exiting City Mog House after job change breaks NPC/Zoning

### ISSUE THREAD

**Issue by Gretal1** [HorizonFFXI/HorizonXI-Issues#661] opened 2023-01-03 00:36 UTC
**What does this bug affect?**
When you exit Mog House after changing jobs, you will not be prompted to set your home point. HUGE indicator you are bugged. You will not be able to examine yourself or others. If you talk to an NPC, you will get stuck with no dialog, you can open text boxes and menus, but cant move. If you try to zone, your screen will start transitioning but you never zone. Your map shows people moving, but you cannot open menus or chat.

**Steps to Reproduce**
1.) Enter a mog house in a CITY.
2.) Change jobs
2.) Exit
3.) If prompted to set home point, re-enter, repeat steps 2, and 3.
4.) If no promt to set home point, examine yourself. talk to an npc, or try to zone.

**Expected behavior**
Change jobs, exit, talk to npc and be able to zone.

**Screenshots**
https://youtu.be/dlEoiV5zRvA

**Setup Information**
Chrome, using current Horizon launcher. Windows 10. 

**Additional context**

**Comment by Gretal1** [comment] 2023-01-03 00:47
https://youtu.be/dlEoiV5zRvA

Link to video above.^

**Comment by HitGubz** [comment] 2023-01-03 16:57
I got this bug in Jeuno without ever exiting the mog house. It didn't happen before the moogle started giving me the dialogue about power bow and beetle ring. 

This time I logged into Jeuno MH, Clicked Moogle, Clicked through quest dialogue and got frozen after trying to interact with moogle again.

**Comment by CriticalXI** [comment] 2023-02-10 19:15
Going to close this as a duplicate of an issue on ASB as this problem should be on ASB as well.

Duplicate of AirSkyBoat/AirSkyBoat#2451

**Closed by CriticalXI** 2023-02-10 19:15 UTC
Labels: bug
