### ISSUE TITLE
🐛[BUG][Combat] Rock Crusher 0 damage, TP returns

### ISSUE THREAD

**Issue by SpaggiG** [HorizonFFXI/HorizonXI-Issues#701] opened 2023-01-05 17:04 UTC
**What does this bug affect?**

Staff weaponskill "Rock Crusher" will randomly do 0 damage. Additionally it will also still give full tp as if it hit while still doing 0 damage

**Steps to Reproduce**

Use weaponskill, do 0 damage, get tp.

**Expected behavior**

Weaponskill should do more than 0 damage. And if it does do 0 damage should return 0 tp

**Comment by mousseng** [comment] 2023-02-28 23:22
this also happens with the dagger weaponskill Cyclone. haven't found any particular rhyme or reason, but i'm happy to guinea pig for interested devs.
![image](https://user-images.githubusercontent.com/8106757/222005262-edf293c8-17cd-43aa-a2cf-447032a861a1.png)

**Comment by CriticalXI** [comment] 2023-04-18 16:57
Duplicate of #709 

Other ticket has more general information about the issue

**Closed by CriticalXI** 2023-04-18 16:57 UTC
Labels: bug, Combat
