### ISSUE TITLE
🐛[BUG][Mission] BCNM 40 Undying Promise Qu'Bia Arena DOESN'T WORK

### ISSUE THREAD

**Issue by Boilon** [HorizonFFXI/HorizonXI-Issues#852] opened 2023-01-17 03:25 UTC
**What does this bug affect?**
Party Members CANNOT zone in to BCNM after orb user goes in. This left me (orb user) stuck inside the BCNM by myself with party members unable to zone in to battlefield. Tried logging out and then battlefield timer went away and being stuck inside the arena.

**Steps to Reproduce**
Trading Star Orb to BCNM circle in Qu'Bia Arena and entering Undying Promise. Doesn't seem consistent because some other people have been able to do it.

**Expected behavior**
Party members should be able to enter?

**Screenshots**
![Boilon_2023 01 16_190731](https://user-images.githubusercontent.com/122848725/212803100-8c624f8e-a7cc-4f14-acf3-8f4b242e7e10.png)
![Boilon_2023 01 16_191827](https://user-images.githubusercontent.com/122848725/212803107-a2f432c2-0abe-4204-b86d-5337aac60bdf.png)

**Additional context**
It seems that other people are able to do this and not get bugged out, it seems inconsistent. Because another group of 3 BSTS came after me and were able to. In fact I was still INSIDE the BCNM while they were fighting the skeleton.

**Comment by CriticalXI** [comment] 2023-03-06 19:51
Duplicate of #821

**Closed by CriticalXI** 2023-03-06 19:51 UTC
Labels: bug
