### ISSUE TITLE
🐛[BUG][Combat]Scorpion TP Move "Wild Rage" Wipes Shadows.  Should be absorbed by 2.

### ISSUE THREAD

**Issue by HorizonPotato** [HorizonFFXI/HorizonXI-Issues#1397] opened 2023-04-11 05:45 UTC
**What does this bug affect?**
Scorpion TP move, "Wild Rage".

**Steps to Reproduce**
1) Have 3+ Shadows up
2) Scorpion uses Wild Rage.  Wipes all shadows, deals damage.

**Expected behavior**
Wild Rage - Absorbable by 2 Utsu Shadows.

**Screenshots**
https://www.youtube.com/watch?v=H80aW1Unx3I --- Era Accurate Video of ODS since its the only Scorpion video I could find.  You can see at about the 1:23~1:25 Mark, a Scorpion uses Wild Rage and one of their members has the message "2 of Atilathehunts shadows absorb the damage and disappear"

**Setup Information**
Current

**Additional context**
Was doing ODS and it felt very difficult and as a THF/NIN I felt like I was getting rolled by Damage.  Then I realized, Wild Rage was wiping shadows when it should be absorb by 2 shadows.   Wild Rage is extremely dangerous in ODS on the last ~2 scorpions and can deal upward 900 damage to DPS jobs, and this is a huge bump in the KSNMs difficulty.  Makes the only safe job for these BST or SMN...

**Comment by CriticalXI** [comment] 2023-04-18 21:15
Duplicate of #1190

**Closed by CriticalXI** 2023-04-18 21:15 UTC
Labels: bug
