### ISSUE TITLE
🐛[BUG][Quest] Got Cutscene for At the Heavens' Door (RoV Mission) at Shattered Telepoint

### ISSUE THREAD

**Issue by Shuhasu** [HorizonFFXI/HorizonXI-Issues#1054] opened 2023-02-12 03:08 UTC
**What does this bug affect?**
Cutscene before Promies

**Steps to Reproduce**
Be on CoP 1-2, Click on Promy-Dem Shattered Telepoint

**Expected behavior**
Enter Hall of Transference 

**Screenshots**
https://media.discordapp.net/attachments/1073743090277429329/1073743090495541349/Shessra_2023.02.10_171049.png

**Setup Information**
/version isn't working, but should be up to date as of 2/11/23

**Additional context**
Trying to get promies done and I got this out of order RoV cutscene, but was able to still progress CoP

**Comment by TracentEden** [comment] 2023-02-13 23:46
Duplicate of https://github.com/HorizonFFXI/HorizonXI-Issues/issues/843

**Closed by TracentEden** 2023-02-13 23:46 UTC
Labels: bug
