### ISSUE TITLE
🐛[BUG][Combat] Darts play singing animation when thrown.

### ISSUE THREAD

**Issue by jonbonazza** [HorizonFFXI/HorizonXI-Issues#839] opened 2023-01-15 06:36 UTC
**What does this bug affect?**
When you throw a `Dart` it plays the singing animation instead of the throwing animation. It also plays the singing sound effects, so it's quite annoying when trying to skill up throwing.

**Steps to Reproduce**
Simply equip darts, find a mob and make a ranged attack.

**Expected behavior**
It should play the dart throwing animation.

**Screenshots**
Even better. Here's a video.
https://drive.google.com/file/d/1uA-XxNCB_KL1MIMlauYCnY2Dk5PNm8b1/view?usp=sharing
(was too big to embed in the issue 😢 )

**Setup Information**
Windows 11... not sure really what to put in this section. 🤷‍♂️ 

**Additional context**
FWIW, I've only tested this on NIN/WAR. Not sure if it matters (I doubt it)  but thought I'd put it here just in case.

**Comment by CriticalXI** [comment] 2023-03-06 19:19
Duplicate of #452

**Closed by CriticalXI** 2023-03-06 19:19 UTC
Labels: bug
