### ISSUE TITLE
🐛[BUG][NPC Twinkstix]

### ISSUE THREAD

**Issue by Tenkentaru** [HorizonFFXI/HorizonXI-Issues#940] opened 2023-01-26 23:45 UTC
**What does this bug affect?**
Twinkstix not providing OP warp in lower Jueno. Have used it before but not working now. Tried on a 65 BST and 37 WHM. When I interact with him he just says, “Welcome to my magicks service” and then…. That’s it. I see everyone around me using OP but he will not engage with my character further anymore (Character name is Tenken). I contacted a GM and he suggested this issue is beyond the GM team and requires Dev support. 

**Steps to Reproduce**
Very easy to reproduce. I click on the NPC and he says his 1 and then does not further engage. 

**Expected behavior**
He should offer OP warps, as he did previously. 

**Setup Information**
Windows operating system 

**Additional context**
Nothing else to add other than I can’t access OP :( hope to find a fix. Thanks dev team!

**Comment by CriticalXI** [comment] 2023-03-06 20:16
Duplicate of #910

**Closed by CriticalXI** 2023-03-06 20:16 UTC
Labels: bug
