### ISSUE TITLE
🐛[BUG] Lvl 60 avatar trial fights

### ISSUE THREAD

**Issue by Squinkerdoodle** [HorizonFFXI/HorizonXI-Issues#354] opened 2022-11-01 04:32 UTC
**What does this bug affect?**
Avatars will repeatedly use a physical BP until it uses a magic BP which breaks the cycle, after which the avatar will continue to auto attack. This doesn't happen every time, but does seem to be a common occurrence. When testing this I did not use the !tp command and waited for the avatars to naturally build TP.

Additionally avatars seem to either only use their lvl 70 bp /  lvl 75 merit bp / tier 4 magic BP,  or they will only use their lvl 1 BP and tier 2 magic BPs.

When I tested Leviathan Prime it was only using it's level 1 BP (Barracuda Dive) and it's tier 2 magic BP.

**Steps to Reproduce**
Go into lvl 60 avatar fight and smack the avatar until it uses a physical BP.

**Expected behavior**
 Avatars should only use 1 BP instead of being able to chain physical BPs back to back, and should be able to use more BPs aside from the lvl 75 / merit / tier 4 BPs.

**Screenshots**
![image](https://user-images.githubusercontent.com/112344508/199154137-da14b84f-ef35-4ae6-ba1e-52358342c217.png)
![image](https://user-images.githubusercontent.com/112344508/199154327-c2156ce3-9023-44c9-9ba9-0ef2888e1535.png)
![image](https://user-images.githubusercontent.com/112344508/199154912-c58ddc41-bfda-406b-8578-bd75f4d07ff1.png)
![image](https://user-images.githubusercontent.com/112344508/199159292-1635790d-413f-49e2-affa-fe60104f52e0.png)

**Setup Information**
Version 30221004_0

**Additional context**
I did not check all the fights, but since 3 had the same issue I'm assuming the same is for the other 3 as well.

**Comment by xkoredev** [comment] 2022-11-07 01:59
This is a dupe of https://github.com/AirSkyBoat/AirSkyBoat/issues/472 and was fixed with https://github.com/LandSandBoat/server/pull/3141

**Closed** 2022-11-07 02:01 UTC
Labels: bug
