### ISSUE TITLE
Cannot obtain Conquest point item: Royal Knight's Breeches

### ISSUE THREAD

**Issue by shon81** [HorizonFFXI/HorizonXI-Issues#1005] opened 2023-02-03 02:20 UTC
Cannot purchase a Rank 6 Conquest item from any guard. I am rank 6. When I try to obtain the item I get the response:

Your rank is too low to purchase the .

The item is Royal Knight's breeches.

**Comment by bliven-was-taken** [comment] 2023-02-03 14:24
It requires Sandy in 1st place.

**Comment by TracentEden** [comment] 2023-02-04 17:38
Duplicate of https://github.com/HorizonFFXI/HorizonXI-Issues/issues/991

**Closed by TracentEden** 2023-02-04 17:38 UTC
