### ISSUE TITLE
🐛[BUG][Combat] Casting spells resetting TP to 0 

### ISSUE THREAD

**Issue by alessa89** [HorizonFFXI/HorizonXI-Issues#484] opened 2022-12-09 16:22 UTC
**What does this bug affect?**
this only seems to be impacting one of my characters, had a few other players test, they see it happening to me, but doesn't happen to them.  when i cast spells, any tp i have goes down to 0. this is without any gm commands running, no wacky equipment, happened with addons disabled, goto myself/complete relog into zone etc

**Steps to Reproduce**
get some tp, cast a spell

**Expected behavior**
not this :( 

**Screenshots**
![image](https://user-images.githubusercontent.com/115948656/206746043-1fa53bd6-5f31-4a4b-bf6b-d220391a7a43.png)

![image](https://user-images.githubusercontent.com/115948656/206746119-42f1d919-d676-44d3-b90d-4cba89604c0a.png)

**Setup Information**
version 30221103_1

**Additional context**
screenshots above might be small, me at 1000 tp, cast dia on a worm, go down to 0 tp, can provide more reference if needed. probably lower priority as so far this only seems to be impacting one of my characters and no one else

**Comment by panicstevenson** [comment] 2022-12-10 03:20
I can't reproduce.

**Comment by OpheliaXI** [comment] 2022-12-10 05:07
Unable to reproduce as well. Potentially a race condition? However we don't have any indication as to what it may be.

**Comment by StyrkaGG** [comment] 2022-12-10 13:54
i cant reproduce this either by chance was a macro swapping weapon?

**Comment by alessa89** [comment] 2022-12-10 15:29
race in this case was taru ophelia, and styrka, no macro just straight casting from the menu

public mentioned there are some issues with smn and warping around that may have permanently messed up some values on this character despite the job change. couldn't find anyone else this has been effecting, maybe just more weird alessa shit

**Comment by Shuu-37** [comment] 2022-12-10 22:36
Closing as unable to repro. Feel free to reopen if encountered again.

**Closed by Shuu-37** 2022-12-10 22:36 UTC
Labels: bug, P0 (Blocking)
